### ISSUE TITLE
testLiquidateVaultFactory test should be upgraded to work with the packed slots update

### ISSUE THREAD

**Issue by simluyt** [arcadia-finance/arcadia-vaults#104]
Currently waiting for an update in the forge std library that allows us to change specific data in a structure w cheat codes

PR is in and will probably merge within next few weeks.

**Comment by Thomas-Smets** [comment]
@simluyt Can we do this with an extension contract as in 8_Vault.t.sol?

**Comment by simluyt** [comment]
Yes by overwriting visibility riight?

**Comment by Thomas-Smets** [comment]
Or by adding a new function in the extension that directly modifies the required state variables?
